### PR TITLE
Labels for xair-remote

### PR DESCRIPTION
**Pull request by BeansIsFat**
Labels for xair-remote and preview of how labels look on the device. Print the labels at 100% scale on full size A4 or US Letter label paper, cut, and apply to X-Touch Mini.

### CODE REVIEW

**Comment by peterdikant** [comment]
Looking good, but I believe the overview pdf contains a copyrighted image. I don't think it is allowed to include this in the project.

And the labels are quite specific for you (mute group naming). The pdf is also not editable. So I would very much prefer a format that anyone could edit. Google Spreadsheet might be ideal or maybe Excel.

**Comment by BeansIsFat** [comment]
Thanks for the feedback. If it's helpful I can make the mute groups generic
and see about implementing something in an Excel file. I enjoy using your
software and wanted to contribute to the user experience.

**Comment by peterdikant** [comment]
I appreciate that, thanks a lot! Yes, it would be great if you could use generic names for the mute groups and also commit your source file together with the pdf.

**Review by peterdikant — CHANGES_REQUESTED** [review]
This revert commit is wrong. You did revert a bug fix that prevents a crash.

**Comment by peterdikant** [comment]
I have now created an excel template. Excel should be widely available and it is easy to customize the labels to your own liking.

I will close this pull request as it is no longer needed. Thanks for your input!

**Pull request closed without merging**
